
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package archivos.sintactico;

/** CUP generated class containing symbol constants. */
public class MiParserSym {
  /* terminals */
  public static final int INT = 10;
  public static final int COMA = 3;
  public static final int POTENCIA = 12;
  public static final int SUMA = 2;
  public static final int MULT = 5;
  public static final int PARENTESISC = 8;
  public static final int ERROR = 9;
  public static final int RAIZ = 13;
  public static final int EOF = 0;
  public static final int ABS = 14;
  public static final int DIV = 6;
  public static final int error = 1;
  public static final int PARENTESISO = 7;
  public static final int RESTA = 4;
  public static final int FLOAT = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMA",
  "COMA",
  "RESTA",
  "MULT",
  "DIV",
  "PARENTESISO",
  "PARENTESISC",
  "ERROR",
  "INT",
  "FLOAT",
  "POTENCIA",
  "RAIZ",
  "ABS"
  };
}

